<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.13" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Abstractions/BuildingBlocks.Abstractions.csproj" />
    <ProjectReference Include="../../modules/auth/domain/Auth.Domain.csproj" />
    <ProjectReference Include="../../modules/user_data/domain/Users.Domain.csproj" />
    <ProjectReference Include="../../modules/product/domain/Products.Domain.csproj" />
    <ProjectReference Include="../../modules/category/domain/Categories.Domain.csproj" />
    <ProjectReference Include="../../modules/payment/domain/Payments.Domain.csproj" />
    <ProjectReference Include="../../modules/task/domain/Tasks.Domain.csproj" />
    <ProjectReference Include="../../modules/project/domain/Projects.Domain.csproj" />
  </ItemGroup>

</Project>
